### ISSUE TITLE
Documentation Tracking Issue

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#131]
- [x] Description of all public interfaces
- [ ] All docs (within reason) have inline code examples
- [ ] Code example for loading custom fonts
- [x] Passing doctests
- [ ] User plugin example and walkthrough
